---
title: Отчет за неделю от VC.ru
author: 
output:
  html_document: 
    df_print: kable
---

```{r set-options, include = FALSE}
#Sys.setlocale("LC_CTYPE", "russian")
Sys.setlocale("LC_ALL", "russian")
```

```{r, results='asis', include = FALSE}
library(httr)
library(jsonlite)
library(dplyr)
library(lubridate)
library(kableExtra)


```


```{r, include = FALSE}
vc_api <- function(path){
    url <- modify_url("https://api.vc.ru/", path = path)
    resp <- GET(url)
    parsed <- jsonlite::fromJSON(content(resp, "text"), simplifyVector = FALSE)
    
    structure(
        list(
            content = parsed,
            path = path,
            response = resp
        ),
        class = "VC_api"
    )
}


print.vc_api <- function(x, ...) {
    cat("<vc_api ", x$path, ">\n", sep = "")
    str(x$content)
    invisible(x)
}
```

```{r, echo = F}
get_popular <- function(period = "week"){
    url <- paste0("v1.8/timeline/mainpage/", period)
    mainpage <- vc_api(url)
    titles <- sapply(mainpage$content$result, function(x){x$title})
    hits <- sapply(mainpage$content$result, function(x){x$hitsCount})
    link <- sapply(mainpage$content$result, function(x){x$url})
    title_md <- paste0("[", titles, "]", "(", link, ")")
    img <- sapply(mainpage$content$result, function(x){x$cover$url})
    img_type <- sapply(mainpage$content$result, function(x){x$cover$additionalData$type})
    img_md <- c()
    for(i in 1:length(img)){
      if(img[i] != "NULL"){
        if(img_type[i] == "jpg" | img_type[i] == "png"){
          img_md[i] <- paste("!","[image]","(", img[i], ")", sep = "")
        } else {
          img_md[i] <- ""
        }
      } else{
         img_md[i] <- ""
      }
    }
    pub_date <- sapply(mainpage$content$result, function(x){x$date})
    brief <- sapply(mainpage$content$result, function(x){x$summarize})
    id <- seq()
    together <- tibble(title = title_md,
                       summary = brief,
                       hits = hits, 
                       image = img_md,
                       date = strftime(as_datetime(pub_date), "%d %b")) %>%
      arrange(desc(hits)) %>%
      mutate(id = seq_along(title)) %>%
      relocate(id)
    return(together)
}
together <- get_popular()
together <- slice(together, 1:10)
```


```{r, echo = F}
kable(together, col.names = c("№",
                              "Заголовок",
                              "Краткое содержание",
                              "Просмотры",
                              "Картинка",
                              "Дата"),) %>%
  kable_styling(bootstrap_options = c("striped"), fixed_thead = T) %>%
  column_spec(2, width = "18em") %>%
  column_spec(6, width = "4em")
```